### PR TITLE
fix for vtk output when N_SMOKE3D = 0

### PR DESCRIPTION
**Pull request by johodges**

### CODE REVIEW

**Comment by johodges** [comment]
Give me a minute to push up another change here for the paraview statefile output.

**Comment by marcosvanella** [comment]
Sure, thanks!
________________________________

**Comment by johodges** [comment]
Ok should be good to go. Now the paraview state file that is generated by FDS is read appropriately by paraview with the duct_flow case.

**Comment by marcosvanella** [comment]
Ok excellent, I'll give it a try. Thanks!

**Comment by marcosvanella** [comment]
something to look at tomorrow, in the same duct_flow.fds case I added WRITE_STL=T in &DUMP and got this:

 Completed reading of input file                    CPU Time:   0.040
 Completed Initialization Step 1                    CPU Time:   0.040

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0xbcfd9423960 in ???
#1  0xbcfd9422ac5 in ???
#2  0xbcfd904251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0xd2e1b423960 in ???
#1  0xd2e1b422ac5 in ???
#2  0xd2e1b04251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0x130763a23960 in ???
#1  0x130763a22ac5 in ???
#2  0x13076364251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0xc0ee5423960 in ???
#1  0xc0ee5422ac5 in ???
#2  0xc0ee504251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0x147294623960 in ???
#1  0x147294622ac5 in ???
#2  0x14729424251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0xd8709023960 in ???
#1  0xd8709022ac5 in ???
#2  0xd8708c4251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0x8fa04e23960 in ???
#1  0x8fa04e22ac5 in ???
#2  0x8fa04a4251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#0  0xdbf00423960 in ???
#1  0xdbf00422ac5 in ???
#2  0xdbf0004251f in ???
      at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x6542fddca240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x6542fddca860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x6542fddc8bc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#3  0x5e8566d07240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x5e8566d07860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x5e8566d05bc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#3  0x5d60b815e240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x5d60b815e860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x5d60b815cbc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#3  0x5aa6c226e240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x5aa6c226e860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x5aa6c226cbc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#3  0x559110b8a240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x559110b8a860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x559110b88bc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#3  0x570e3c08c240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x570e3c08c860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x570e3c08abc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#3  0x62d7d62e1240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x62d7d62e1860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x62d7d62dfbc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#6  0x6542fe05ed92 in fds
      at ../../Source/main.f90:163
#7  0x6542fe10ad67 in main
      at ../../Source/main.f90:6
#6  0x5e8566f9bd92 in fds
      at ../../Source/main.f90:163
#7  0x5e8567047d67 in main
      at ../../Source/main.f90:6
#6  0x5aa6c2502d92 in fds
      at ../../Source/main.f90:163
#7  0x5aa6c25aed67 in main
      at ../../Source/main.f90:6
#6  0x570e3c320d92 in fds
      at ../../Source/main.f90:163
#7  0x570e3c3ccd67 in main
      at ../../Source/main.f90:6
#6  0x5d60b83f2d92 in fds
      at ../../Source/main.f90:163
#7  0x5d60b849ed67 in main
      at ../../Source/main.f90:6
#6  0x559110e1ed92 in fds
      at ../../Source/main.f90:163
#7  0x559110ecad67 in main
      at ../../Source/main.f90:6
#6  0x62d7d6575d92 in fds
      at ../../Source/main.f90:163
#7  0x62d7d6621d67 in main
      at ../../Source/main.f90:6
#3  0x608ebd12a240 in calc_normal
      at ../../Source/dump.f90:1630
#4  0x608ebd12a860 in write_facet
      at ../../Source/dump.f90:1607
#5  0x608ebd128bc6 in __dump_MOD_write_stl_file
      at ../../Source/dump.f90:1556
#6  0x608ebd3bed92 in fds
      at ../../Source/main.f90:163
#7  0x608ebd46ad67 in main
      at ../../Source/main.f90:6
________________________________

**Comment by johodges** [comment]
Interesting, I'll take a look

**Comment by marcosvanella** [comment]
I'm thinking the issue might be due to having 0 thickness obsts in duct_flow.
________________________________

**Comment by johodges** [comment]
Yep it was an issue with thin obstructions. Pushing a fix now.

**Comment by johodges** [comment]
Note I also reverted one of the changes I did in the prior PR about making the TITLE inherit FN_LENGTH. The TITLE needs to be a CHAR(80) for the STL format. We'll need to decide how to truncate that later.

**Comment by marcosvanella** [comment]
Jon, I'm back on this. Do you need to do another PR besides the one on TITLE I just accepted?
Thanks.

**Comment by johodges** [comment]
Nope, I think the WRITE_STL feature should be working again. Let me know if you run into another issue.

**Comment by johodges** [comment]
Also, the generated paraview state file should auto-import the STL as well.

**Comment by marcosvanella** [comment]
Ok, thanks I wasn't sure. Working on my iMac in both cases we were looking at yesterday. 
I'll do the change to the send recv now. I'll download paraview here and when you have time next week we can do a fast tutorial. Also, WRITE_BINARY should be working correct? Thinking we want that enabled in frontier runs.

**Comment by johodges** [comment]
correct, WRITE_BINARY should be working as well. I'll double check with the duct case real quick

**Comment by marcosvanella** [comment]
Also, I just asked Oak Ridge help to add you as user on our project with the Frontier allocation. We'll need the viz expert for this monster calculation we are planning :)

**Comment by johodges** [comment]
Sounds good. I guess I will need to make sure I still remember my login info!

**Comment by johodges** [comment]
Yes the binary output is working as well for the duct case.

**Comment by marcosvanella** [comment]
Nice, thanks!

**Comment by marcosvanella** [comment]
I'm still picking up this error with the intel debug version 2021.7 in my Mac. I'll try the case in the linux laptop and latest ifort. Other issues are clean now.

 Completed particle initialization                  CPU Time:   0.303
 Completed INITIALIZE_GLOBAL_DUMPS                  CPU Time:   0.306
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable RAW when it is not allocated

Image              PC                Routine            Line        Source             
libifcoremt.dylib  0000000116AE7780  Unknown               Unknown  Unknown
fds_ompi_intel_os  000000010FE47B79  _stringifor_strin        7136  vtkf.f90
fds_ompi_intel_os  000000010FF19CA6  _vtkf_file_xml_wr       11480  vtkf.f90
fds_ompi_intel_os  000000010FF09207  _vtkf_file_xml_wr       11200  vtkf.f90
fds_ompi_intel_os  000000010FF4F8B7  _vtk_fortran_vtk_       12319  vtkf.f90
fds_ompi_intel_os  00000001102E3303  _dump_mp_dump_slc        6655  dump.f90
fds_ompi_intel_os  000000010FF97544  _dump_mp_dump_mes         144  dump.f90
fds_ompi_intel_os  0000000110C40976  _MAIN__                   533  main.f90
fds_ompi_intel_os  000000010BB1D10E  Unknown               Unknown  Unknown
dyld               00007FF81825A386  Unknown               Unknown  Unknown
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable RAW when it is not allocated

**Comment by marcosvanella** [comment]
Jon try the duct_flow.fds case in your linux machine with latest Intel compiler and **impi_intel_linux_db** target. I set 
&DUMP DT_VTK=0.5 WRITE_STL=T/
This is what I see:
 Completed VELOCITY_BC match                        CPU Time:   0.639
 Completed radiation initialization                 CPU Time:   0.712
 Completed particle initialization                  CPU Time:   0.774
 Completed INITIALIZE_GLOBAL_DUMPS                  CPU Time:   0.775
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable RAW when it is not allocated

Image              PC                Routine            Line        Source             
fds_impi_intel_li  00000000038F2633  stringifor_string        7136  vtkf.f90
fds_impi_intel_li  000000000399CCDA  vtkf_file_xml_wri       11480  vtkf.f90
fds_impi_intel_li  000000000398F255  vtkf_file_xml_wri       11200  vtkf.f90
fds_impi_intel_li  00000000039C7B28  vtk_fortran_vtk_f       12319  vtkf.f90
fds_impi_intel_li  0000000003C78FA1  dump_mp_dump_slcf        6655  dump.f90
fds_impi_intel_li  00000000039FE1D1  dump_mp_dump_mesh         144  dump.f90
fds_impi_intel_li  000000000438F1E2  MAIN__                    533  main.f90
fds_impi_intel_li  0000000000407A1D  Unknown               Unknown  Unknown
libc.so.6          000010E3CFA29D90  Unknown               Unknown  Unknown
libc.so.6          000010E3CFA29E40  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000407935  Unknown               Unknown  Unknown

**Comment by marcosvanella** [comment]
I run with single MPI process. With 8 it also fails.

**Comment by johodges** [comment]
I will take a look

**Comment by marcosvanella** [comment]
what is puzzling is that I only see this with intel compiler in debug mode. Intel optimized and gnu targets work.
I'm going to push the fix to the send/recv operations to get us going in frontier.

**Comment by johodges** [comment]
That is really odd. I have some changes I need to make to the guides, but I'll try to look at this more tomorrow. It will probably be the afternoon before I can get to it.

**Comment by marcosvanella** [comment]
That fine, Eric is running with optimized gnu and ifort on several machines (frontera,polaris,frontier) so we should be good.

________________________________

**Comment by johodges** [comment]
Just getting back to this. This is a weird case!

**Comment by johodges** [comment]
Ok, I understand what is going on. I added a line to the library to trick the intel compiler into thinking a variable was used so that it would build in debug mode. This was working ok before, but I had not been trying to actually run the model in debug mode. When we try and run in debug mode the vtkf library has a custom string compare option that is complaining because the way I tricked the compiler was invoking a string compare that was not compatible.  I can remove this string compare which will fix this issue but just need to find another way to trick the compiler into thinking the variable is used.

**Comment by marcosvanella** [comment]
Hi Jon, all right, I'll merge your PR and let you know. Thanks!

**Pull request merged**
