### PR TITLE
Fix for overflow in slcf name with vtk out

### PR DESCRIPTION
**Pull request by johodges**

### CODE REVIEW

**Comment by marcosvanella** [comment]
Jon, try the latest source with gcc and openmpi. This is what I see setting DT_VTK=0.5 in Pressure_Solver/duct_flow.fds

 Completed Poisson initialization                   CPU Time:   0.111
 Completed COMPUTE_VISCOSITY                        CPU Time:   0.118
 Completed VELOCITY_BC match                        CPU Time:   0.125
 Completed radiation initialization                 CPU Time:   0.128
 Completed particle initialization                  CPU Time:   0.133
 Completed INITIALIZE_GLOBAL_DUMPS                  CPU Time:   0.134
At line 4539 of file ../../Source/dump.f90
Fortran runtime error: Allocatable actual argument 'a_vtk_file' is not allocated

Error termination. Backtrace:
At line 4539 of file ../../Source/dump.f90
Fortran runtime error: Allocatable actual argument 'a_vtk_file' is not allocated

Error termination. Backtrace:
At line 4539 of file ../../Source/dump.f90
Fortran runtime error: Allocatable actual argument 'a_vtk_file' is not allocated

Error termination. Backtrace:
At line 4539 of file ../../Source/dump.f90
Fortran runtime error: Allocatable actual argument 'a_vtk_file' is not allocated
________________________________
From: johodges ***@***.***>
Sent: Thursday, February 22, 2024 05:29 PM
To: marcosvanella/fds ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [marcosvanella/fds] Fix for overflow in slcf name with vtk out (PR #10)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/marcosvanella/fds/pull/10

Commit Summary

  *   7b4a0cc<https://github.com/marcosvanella/fds/pull/10/commits/7b4a0cc283f96c2abd2bf214a28d3d0ba68a787f> minor edits to new spyro writeup in tech guide
  *   c82173e<https://github.com/marcosvanella/fds/pull/10/commits/c82173e753b7060b884cd9aea26394cfbd44f8f6> Merge pull request #12518 from johodges/master
  *   775d568<https://github.com/marcosvanella/fds/pull/10/commits/775d56873b4c5126bafaa4b9f190d83ae0945abc> FDS Source: Cosmetic changes only for formatting, indenting
  *   f9d8fec<https://github.com/marcosvanella/fds/pull/10/commits/f9d8fec34dae5c3897070d716dc308090d1f97d7> Merge pull request #12522 from mcgratta/master
  *   5d36857<https://github.com/marcosvanella/fds/pull/10/commits/5d36857412fad11feb4a1a08aafbd024e699428a> FDS Source: Cosmetic changes, formatting
  *   50afa7f<https://github.com/marcosvanella/fds/pull/10/commits/50afa7f6e436abd945b194d840a1efc47fd6bce2> Merge pull request #12523 from mcgratta/master
  *   68c1775<https://github.com/marcosvanella/fds/pull/10/commits/68c1775f57f4e542e1e12a880d57862908973751> fix for overflow in slice name with vtk
  *   7b59d1d<https://github.com/marcosvanella/fds/pull/10/commits/7b59d1d9dd4b92d2d8f40335f013772d52dd6ac8> Merge branch 'firemodels:master' into FireX
  *   0ca100d<https://github.com/marcosvanella/fds/pull/10/commits/0ca100da54f7a205bf4a41ecdf4497946c10cbdb> Merge remote-tracking branch 'firex/FireX' into FireX

File Changes

(4 files<https://github.com/marcosvanella/fds/pull/10/files>)

  *   M Manuals/FDS_Technical_Reference_Guide/Appendices.tex<https://github.com/marcosvanella/fds/pull/10/files#diff-2eda65907128951f5a15f91cc927ee51622ca25f45927d29ff08772c22952b5d> (8)
  *   M Manuals/FDS_Technical_Reference_Guide/Solid_Chapter.tex<https://github.com/marcosvanella/fds/pull/10/files#diff-e872b1401b31c92eeec466b04927c2b4aa9afa613a568141721a05ffb42a3416> (8)
  *   M Source/read.f90<https://github.com/marcosvanella/fds/pull/10/files#diff-284759de040cf76249bb9a4fa31f70d7e3efd1e6c8bd70a11a3ff708290a89a4> (18)
  *   M Source/wall.f90<https://github.com/marcosvanella/fds/pull/10/files#diff-45a31e54d8dc2629f3e8ca518fb7676210d876d4ad3569bf98d5974a95a05d8f> (107)

Patch Links:

  *   https://github.com/marcosvanella/fds/pull/10.patch
  *   https://github.com/marcosvanella/fds/pull/10.diff

**Comment by johodges** [comment]
taking a look

**Comment by marcosvanella** [comment]
Seems DUMP_SMOKE3D is called twice, one VTK_OUT=F and the second time VTK_OUT=T. In none of the calls it is going in the DATA_FILE_LOOP. In the second call it does go into the final IF(VTK_OUT) THEN and crashes in this line:
VTK_ERROR = A_VTK_FILE%XML_WRITER%W_DATA(LOCATION='NODE', ACTION='CLOSE')
________________________________

**Comment by johodges** [comment]
Yep, just pushed up a fix. Sending a PR

**Pull request merged**
