### PR TITLE
Merging vtk fixes with FireX

### PR DESCRIPTION
**Pull request by johodges**

### CODE REVIEW

**Comment by marcosvanella** [comment]
Hi Jon, are these the changes you were telling me you wanted to test with firebot?

**Comment by johodges** [comment]
Yes that is correct. There shouldn't be many active changes since all the vtk functionality is off by default. But I had to make some changes in read and dump that I want to run through verification.

**Comment by marcosvanella** [comment]
Ok, I'll merge it and then bring latest firemodels/master changes in if there are any.

**Comment by marcosvanella** [comment]
I had to do some surgery in dump.f90 due to conflicts of some of your changes with this mornings PR #12381 in firemodels/master by Glenn. Whenever you have time, do an update on your FireX branch and check your slice files work properly.

**Comment by johodges** [comment]
Thanks for the heads up. Checking now.

**Comment by johodges** [comment]
Looks like surgery was a success, my test case still looks good.

**Pull request merged**
