### PR TITLE
Fix DT RAMPs for VTK, improve particle VTK outputs, improve paraview state file.

### PR DESCRIPTION
**Pull request by johodges**

### CODE REVIEW

**Comment by johodges** [comment]
Let's hold off on merging for a few. Running into an issue on the firex merged version with mpi.

**Comment by marcosvanella** [comment]
> Let's hold off on merging for a few. Running into an issue on the firex merged version with mpi.

Ok Jon, thanks.

**Comment by johodges** [comment]
Ok should be working now with mpi.

**Comment by marcosvanella** [comment]
Ok, thanks Jon!

**Pull request merged**
